name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy prod
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.TODO_HOST}}
          username: ${{secrets.TODO_USER}}
          key: ${{secrets.TODO_KEY}}
          script: sh todo-deploy.sh
